### ISSUE TITLE
Publish artifact to maven central

### ISSUE THREAD

**Issue by KilianB** [KilianB/JImageHash#32]
For some projects it's more convenient if they do not have to configure JCenter as additional repository. 

e.g. #31

**Comment by KilianB** [comment]
Steps to publish to maven central
1. Make sure <a href="https://github.com/KilianB/JImageHash/blob/bbb54245b0dd21df80878930ed40dcde926bddc3/pom.xml">pom</a> contains all **required** fields 
- [x] groupId
- [x] artifactId
- [x] version
- [ ] name
- [ ] description
- [ ] url
- [x] license
- [x] developers
- [ ] scm

2. Configure OSS Account
  - [x] Create account
  - [ ] Claim namespace (JIRA ticket) *

3. Sign files (link JCenter o Maven Central)

* already created a ticket a while ago but never finished the setup process. Do I need to create an entirely new project? The bintray documentation does not exactly state how far we have to go.

**Comment by vmassol** [comment]
+1 would really help! We'd like to use your library on the XWiki project and it would make our life easier :)

**Comment by vmassol** [comment]
Any idea if you'd have the time to work on this anytime soon? Thanks a lot for your project.

**Comment by ntherning** [comment]
JCenter is [shutting down in a few months](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). Would be great if the artifacts could be pushed to Maven Central.

**Comment by MrPowerGamerBR** [comment]
JCenter is already sunset so you can't use this library anymore unless you compile and publish it yourself

**Comment by KilianB** [comment]
I already started publishing the dependencies to central yesterday e.g. https://github.com/KilianB/UtilityCode and created a new repo to split the examples here: https://github.com/KilianB/JImageHash-Examples.
The workflow to publishing to maven central has been set up over the past two days.
