### ISSUE TITLE
java.lang.NoClassDefFoundError: com/github/kilianB/Require

### ISSUE THREAD

**Issue by tzlisx** [KilianB/JImageHash#37]
java.lang.NoClassDefFoundError: com/github/kilianB/Require

**Comment by jktj** [comment]
How is this closed? I'm still facing the same issue.

**Comment by LiorA1** [comment]
someone solved it ?

**Comment by LiorA1** [comment]
solved by define a new model..

**Comment by lfvepclr** [comment]
I solved it. add to your pom:


        <dependency>
            <groupId>com.github.kilianB</groupId>
            <artifactId>UtilityCode</artifactId>
            <version>1.5.7</version>
        </dependency>
        
        <dependency>
            <groupId>com.github.wendykierp</groupId>
            <artifactId>JTransforms</artifactId>
            <version>3.1</version>
            <classifier>with-dependencies</classifier>
        </dependency>
