### ISSUE TITLE
HashValue as zero.

### ISSUE THREAD

**Issue by SandhyaU95** [KilianB/JImageHash#41]
Hi Kilian,
While generating a hash value for the attached file using the below parameters, resulting in 0.
With the same file, we got hash value: 20282409603651670423947251810304 a few days back.
The same file with different formats[PNG, BMP, GIF, TIFF] also resulting in the hash value 0.
Please let me know if you require additional information.

            HashingAlgorithm hasher = new DifferenceHash(256, Simple);
            Hash hash = hasher.hash(bufferedImage );
            BigInteger hashValue = hash.getHashValue();

![image](https://user-images.githubusercontent.com/57987973/69231454-1bb12d00-0baf-11ea-8ab4-278d6c29c8a1.jpeg)

**Comment by SandhyaUduthala** [comment]
Could you please check this and let me know if you need any information.

**Comment by SandhyaU95** [comment]
Could you please check the above issue that why are we getting hash value as zero.
Please let me know if you need any information.

**Comment by KilianB** [comment]
If this is still true (a 0 hash value) please upload the original file to a file hoster and send me the link (e.g. kilian[at]brachtendorf.dev) 
We can not be sure that github doesn't alter something when uploading the link here. 
The library currently does not support transparency (it will be interpreted as either black or white).

You will not get different hash values using the same image. The computation is deterministic and will by definition return the same hash value for the same input, something like image size, encoding or parameters must have changed.

I have not worked with text input yet. Depending on where the image is sliced you will have a hard time with a single precision difference hash. Maybe try to least do a 2 dimensional pass (double precision)

**Comment by KilianB** [comment]
@SandhyaU95 continuing here to keep the conversation and possible tracking of the issue public so everyone can benefit. 
You got a pdf and want to hash it's content. Can you please provide the code snippet you used to convert the pdf to an image?

**Comment by SandhyaU95** [comment]
Ok. I have sent you the link, please check.
Tried with Double precision too, was getting the same hash value which we get for an empty file.
Used ImageMagick for converting from pdf to jpeg.
Thanks.

**Comment by KilianB** [comment]
If asking questions please refer to: https://stackoverflow.com/help/minimal-reproducible-example
To reproduce and test your issue I need to same input data you are using. I don't know which version of ImageMagick you are using, what parameters, how you load the image into your application.

Here it is important to have the same image data as this is used to compute the hash. Please provide me the actual png or jpeg file.

**Comment by KilianB** [comment]
I received the original image and as expected the following is true

> I have not worked with text input yet. Depending on where the image is sliced you will have a hard time with a single precision difference hash. Maybe try to least do a 2 dimensional pass (double precision)

A 512 difference hash simply has not enough resolution to map the individual features of the text.

# 512 bit
![Hash512](https://user-images.githubusercontent.com/9025925/69408437-2a125c80-0d07-11ea-9c8d-5e7c318a76eb.png)

# 1024bit
![Hash1024](https://user-images.githubusercontent.com/9025925/69408438-2aaaf300-0d07-11ea-8c96-cd451d306f7a.png)

# 2048 bit
![Hash2048](https://user-images.githubusercontent.com/9025925/69408440-2aaaf300-0d07-11ea-92e9-5174dab85ca3.png)


```java 
BufferedImage in = ImageIO.read(new File("2Linepdftojpeg.jpeg"));

//Convert image since input type is a weird custom format
BufferedImage newImage = new BufferedImage(in.getWidth(), in.getHeight(), BufferedImage.TYPE_INT_RGB);

Graphics2D g = newImage.createGraphics();
g.drawImage(in, 0, 0, null);
g.dispose();

HashingAlgorithm hasher = new DifferenceHash(2048, Precision.Simple);
		
Hash hash = hasher.hash(newImage);
BufferedImage imgRepresentation = hash.toImage(3, hasher);

ImageIO.write(imgRepresentation, "png", new File("Hash2048.png"));
```

Your solution is to try different hashing algorithms with different settings and see which fits your need. You will have to adjust your matching threshold accordingly for such images.  Maybe you are looking for a library specialized at text comparison, with OCR support and text comparison using edit distances.

**Comment by SandhyaU95** [comment]
Got the hash value just by changing the bitResolution to > 552.
Thank you.
