### ISSUE TITLE
Comparing different size image

### ISSUE THREAD

**Issue by pavanbachu06** [KilianB/JImageHash#42]
How do we manage to utilize the ImageHashing when the image sizes are different? What would the result when we try to compare the same image of different sizes? If we can implement it, which algorithm do I need to utilize?

**Comment by KilianB** [comment]
The first step of the hashing algorithm resizes and grayscales the input prior to computing the actual hash, therefore different sizes should still be detected as a possible match. 

e.g.

<img src="https://user-images.githubusercontent.com/9025925/36542415-04ca8078-17e1-11e8-9be4-9a90b08c404b.jpg">

and

<img src="https://user-images.githubusercontent.com/9025925/36542413-046d8116-17e1-11e8-93ed-210f65293d51.jpg">

will match.

This is the first part of every algorithm so feel free to experiment. A good way to start are the dHash and pHash

**Comment by pavanbachu06** [comment]
thanks for the response, closing the issue
