### ISSUE TITLE
Can't Find MathUtil or ArrayUtil

### ISSUE THREAD

**Issue by pschaeffer** [KilianB/JImageHash#45]
Hi KilianB, 

I am try to install and build JimageHash under Eclipse. However, many of the imports (for MathUtil and others) are failing. What am I doing wrong? Where would I find MathUtil (actually com.github.kilianB.MathUtil)? Should I already have these packages? 

Thank you

Peter Schaeffer

**Comment by KilianB** [comment]
Utility codes was published to maven central recently, as this library will be within days.  The dependency can be found here: https://github.com/KilianB/UtilityCode
