### ISSUE TITLE
Can I use It in android?

### ISSUE THREAD

**Issue by realchandan** [KilianB/JImageHash#48]

**Comment by KilianB** [comment]
I do not do android development with java and thus I can't give you any feedback if the slim android sdk supports all required functionality. I am not aware of any special culprits you should have when using it.

**Comment by omkar-tenkale** [comment]
I'm getting this error

```
    hash = hasher.hash(getFile());
                         ^
  class file for java.awt.image.BufferedImage not found
```

So i guess we cant use this library in android?

As java awt packages are not supported in android

**Comment by ghost** [comment]
yup you can't! but there are [alternatives](https://github.com/samfch/Perceptual-Image-Similarity)!

**Comment by omkar-tenkale** [comment]
Thanks!
