### ISSUE TITLE
Dockerfile/API implementation?

### ISSUE THREAD

**Issue by JannikZed** [KilianB/JImageHash#5]
Hi @KilianB 
I stumbled upon your project as I was looking for a image similarity service that saves & compares the images using elasticsearch. Unfortunately, I don't have any experience with Java. That's why I wanted to ask you about your opinion on creating a Docker based service out of your project or if you could just estimate, how much effort this would mean. Packing everything up a Dockercontainer, maybe even with a HTTP API would maybe also improve the development process.
Thanks!

**Comment by KilianB** [comment]
I am sorry for the late response. Sadly I do not have any experience with docker, and any estimate given would be highly unreliable. If there is anything I can do to support you feel free to contact me and I'll see if we can figure something out.

Adding an http wrapper surely shouldn't be an issue. It simply depends on what you need and what you want to do.
